name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install numpy scipy matplotlib scikit-learn flake8 pycodestyle pydocstyle pytest-html pytest-xdist

    - name: Lint with flake8
      run: flake8 optns

    - name: Check code style
      run: pycodestyle optns

    - name: Check doc style
      run: pydocstyle optns

    - name: Install package
      run: python -m pip install -e .

    - name: Test with pytest
      run: pytest

    - name: Run Gauss basic example
      run: python examples/gaussprofilefit.py

    - name: Run Gauss example
      run: python examples/gaussoptns.py

    - name: Run Poisson example
      run: python examples/poissonoptns.py
